dbt_project:
  outputs:
    dev:
      dataset: airbyte_ecommerce
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "/home/blackitalian/.ssh/airbyte-bigquery.json" # Update this field with your file name, example: /opt/airflow/service_accounts/airflow-***116-83db69931a10.json
      location: US # Update this field with your dataset location, example: US
      method: service-account
      priority: interactive
      project: elaborate-art-318223 # Update this field with your BigQuery project ID
      threads: 1
      type: bigquery
  target: dev

  