version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: