---

- name: deploy techmax website
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache server
      apt:
        name: apache2
        state: present

    - name: Delete existing /var/www/html directory
      file:
        path: /var/www/html
        state: absent

    - name: Clone web files from GitHub
      git:
        repo: https://github.com/azeezsalu/techmax.git
        dest: /var/www/html

    - name: Start Apache server
      service:
        name: apache2
        state: started
        enabled: yes
